name: Deploy to EC2

on:
  push:
    branches:
      - main  # o la rama que usas para trabajar

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Deploy via SSH
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ubuntu
        key: ${{ secrets.EC2_SSH_KEY }}
        port: 22
        script: |
          cd ~/herencia-app/backend
          git pull
          cd ../frontend
          git pull
          cd ..
          docker-compose up --build -d
